---
title: Soluciones a problemas de _Time Series Analysis and its Applications_ de Shumway y Stoffer
author: Marcelo Molinatti
date: "`r Sys.Date()`"
output:
 html_document:
  number_sections: yes
  keep_md: yes
header-includes:
 - \usepackage{amsmath}
 - \usepackage{amsfonts}
lang: es
---

```{r setup}
library(astsa)
library(ggfortify)
library(kableExtra)

knitr::opts_knit$set(kfigr.prefix=TRUE, kfigr.link=FALSE)
```

* Ejercicios del [capitulo 1](#capitulo-1). Características de series temporales.
* Ejercicios del [capitulo 2](#capitulo-2). Análisis de datos exploratorio.
* Ejercicios del [capitulo 3](#capitulo-3). Modelos ARIMA.

# Capitulo 1.

```{r child = "./Shumway-Stoffer-Solutions-Sections/Shumway-Stoffer-Solutions-Ch1.Rmd"}
```

# Capitulo 2.

```{r child = "./Shumway-Stoffer-Solutions-Sections/Shumway-Stoffer-Solutions-Ch2.Rmd"}
```

# Capitulo 3.

```{r child = "./Shumway-Stoffer-Solutions-Sections/Shumway-Stoffer-Solutions-Ch3.Rmd"}
```

# Capitulo 4.

# Capitulo 5.

```{r child = "./Shumway-Stoffer-Solutions-Sections/Shumway-Stoffer-Solutions-Ch5.Rmd"}
```

<!---
[19/4 7:15 p. m.] Marcano: https://rpubs.com/jrodriguezmam/series_temporales
[19/4 7:45 p. m.] Marcano: https://rpubs.com/Aeoiu2019/890500
[22/4 7:07 a. m.] Marcano: https://youtu.be/CIAbHnsfj4A
[22/4 7:07 a. m.] Marcano: Buen día para ayudarlos a tener el proyecto para esta semana ahora pueden usar inteligencia artificial
[22/4 7:23 a. m.] Marcano: https://youtu.be/lUb6lHZVJvU

https://www.youtube.com/watch?v=emF1iBcni0U&ab_channel=AnaMetriks
https://liclourdescuellar.ruplayers.com/
https://finance-r.netlify.app/quantmod.html
-->